const animeData=[{title:"Ao Haru Ride",imageUrl:"AnimeImages/Ao_Haru_Ride_1.jpg",releaseYear:"2014",studio:"Production I.G",synopsis:"While most young girls make an effort to show off their feminine charms, Futaba Yoshioka deliberately behaves like she wants to repel anyone who might be attracted to her. Ostracized by her female classmates in middle school for being a little too popular with the boys, she desperately strives to avoid a similar situation in high school by being unnecessarily noisy and graceless."},{title:"Ao no Hako ( Blue Box )",imageUrl:"AnimeImages/Ao_no_hako.png",releaseYear:"2024",studio:"Telecom Animation Film",synopsis:"Taiki Inomata, a third-year student in junior high, attends Eimei Academy, an integrated school with a major sports program. Having joined the high school badminton team, Taiki tries to attend open practice as early as possible. But no matter how early he goes, he always arrives second in the gymnasium. The person one step ahead of him is Chinatsu Kano, a first-year student in senior high and Taiki's crush."},{title:"Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",imageUrl:"AnimeImages/Kaguya-sama wa Kokurasetai Tensai-tachi no Renai Zunousen.png",releaseYear:"2019",studio:"A-1 Pictures",synopsis:"Considered a genius due to having the highest grades in the country, Miyuki Shirogane leads the prestigious Shuchiin Academy's student council as its president, working alongside the beautiful and wealthy vice president Kaguya Shinomiya. The two are often regarded as the perfect couple by students despite them not being in any sort of romantic relationship."}];function fetchImageResolution(e,t){let a=new Image;a.src=e,a.onload=function(){let e=`${a.naturalWidth}x${a.naturalHeight}`;t(e)},a.onerror=function(){t("Unknown")}}function displayAnimeGallery(e){let t=document.getElementById("animeGallery");t.innerHTML="",e.forEach(e=>{fetchImageResolution(e.imageUrl,a=>{let s=`
                <div class="card">
                    <img src="${e.imageUrl}" alt="${e.title}">
                    <div class="action-buttons">
                        <button class="info-button" title="Show Information">
                            <span class="material-symbols-outlined">description</span>
                        </button>
                        <button class="download-button" title="Download Cover">
                            <span class="material-symbols-outlined">download</span>
                        </button>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">${e.title}</h5>
                        <p class="resolution">Resolution: ${a}</p>
                    </div>
                    <div class="anime-info">
                        <p><strong>Release:</strong> ${e.releaseYear}</p>
                        <p><strong>Studio:</strong> ${e.studio}</p>
                        <p><strong>Synopsis:</strong> ${e.synopsis}</p>
                    </div>
                </div>`;t.insertAdjacentHTML("beforeend",s);let o=t.getElementsByClassName("card"),n=o[o.length-1],i=n.querySelector(".info-button"),r=n.querySelector(".download-button"),l=n.querySelector(".anime-info"),c=n.querySelector("img");i.addEventListener("click",e=>{e.stopPropagation();let t=l.classList.contains("show");if(t)l.classList.remove("show");else{document.querySelectorAll(".anime-info.show").forEach(e=>{e!==l&&e.classList.remove("show")});let a=c.offsetHeight;l.style.height=`${a}px`,l.classList.add("show")}}),r.addEventListener("click",()=>{window.open(e.imageUrl,"_blank")})})})}document.addEventListener("click",e=>{e.target.closest(".info-button")||e.target.closest(".anime-info")||document.querySelectorAll(".anime-info.show").forEach(e=>{e.classList.remove("show")})});const searchInput=document.getElementById("searchInput"),sortSelect=document.getElementById("sortSelect");function sortAnimeList(e,t){return e.sort((e,a)=>e.title.toLowerCase()<a.title.toLowerCase()?"asc"===t?-1:1:e.title.toLowerCase()>a.title.toLowerCase()?"asc"===t?1:-1:0)}function updateGallery(){let e=searchInput.value.toLowerCase(),t=sortSelect.value,a=animeData.filter(t=>t.title.toLowerCase().includes(e));t&&(a=sortAnimeList(a,t)),displayAnimeGallery(a)}searchInput.addEventListener("input",updateGallery),sortSelect.addEventListener("change",updateGallery);const modeToggle=document.getElementById("modeToggle"),prefersDarkScheme=window.matchMedia("(prefers-color-scheme: dark)"),storedTheme=localStorage.getItem("theme");let currentTheme=storedTheme||(prefersDarkScheme.matches?"dark":"light");function applyTheme(e){"system"===e?prefersDarkScheme.matches?document.body.setAttribute("data-theme","dark"):document.body.setAttribute("data-theme","light"):document.body.setAttribute("data-theme",e)}function updateToggleIcon(e){"light"===e?modeToggle.textContent="light_mode":"dark"===e?modeToggle.textContent="dark_mode":modeToggle.textContent="settings"}modeToggle.addEventListener("click",function(){switch(currentTheme){case"light":currentTheme="dark";break;case"dark":currentTheme="system";break;default:currentTheme="light"}applyTheme(currentTheme),localStorage.setItem("theme",currentTheme),updateToggleIcon(currentTheme)}),prefersDarkScheme.addEventListener("change",e=>{let t=localStorage.getItem("theme");"system"===t&&applyTheme("system")}),applyTheme(currentTheme),updateToggleIcon(currentTheme),displayAnimeGallery(sortAnimeList([...animeData],sortSelect.value));